# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ui-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        # Thêm working-directory để chạy lệnh trong thư mục con
        working-directory: ./frontend  # <--- THAY 'frontend' BẰNG TÊN THƯ MỤC CHỨA package.json CỦA BẠN
        run: |
          npm install
          npm run build --if-present
          # npm run test --if-present # Bạn có thể bỏ qua test nếu không cần

      - name: Zip artifact for deployment
        # Chuyển vào thư mục build output và chỉ nén nội dung bên trong nó
        working-directory: ./frontend/dist # <--- THAY 'frontend/dist' BẰNG ĐƯỜNG DẪN ĐÚNG TỚI THƯ MỤC BUILD OUTPUT
        run: zip ../../release.zip . -r # Nén nội dung vào file release.zip ở gốc repo

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip # Upload file zip từ thư mục gốc

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app # Tải về file release.zip

      # Không cần giải nén nếu dùng package: release.zip bên dưới

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C5AA943FC884443581D6AACBE3FAB4D4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9D08002EA8CF453893942B56FADB1F6D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DE9C27CD309E4591AB162169CC3F1E6B }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ui-app'
          slot-name: 'Production'
          # Deploy trực tiếp file zip đã được chuẩn bị đúng
          package: release.zip # <--- Sửa tham số package thành tên file zip
