name: Deploy index.html to Azure Web App - ui-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Bắt buộc cho đăng nhập OpenID Connect
      contents: read # Bắt buộc cho actions/checkout

    steps:
      # Bước 1: Checkout code (lấy file index.html)
      - uses: actions/checkout@v4

      # Bước 2: Nén file index.html thành file zip (cách an toàn để deploy)
      - name: Zip index.html for deployment
        run: zip release.zip ./index.html

      # Bước 3: Đăng nhập vào Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C5AA943FC884443581D6AACBE3FAB4D4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9D08002EA8CF453893942B56FADB1F6D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DE9C27CD309E4591AB162169CC3F1E6B }}

      # Bước 4: Deploy file zip lên Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ui-app' # Tên Web App của bạn
          slot-name: 'Production' # Slot triển khai
          package: release.zip # Chỉ định file zip chứa index.html để deploy
